### PR TITLE
New york times clone

### PR DESCRIPTION
**Pull request by evansinho**
We have completed the new york times project and we need your review before merging it to the master branch. We'll be waiting for your response.

### CODE REVIEW

**Comment by Dandush03** [comment]
# :red_circle: Status: Required Changes  :red_circle:
### Hey @evansinho & @ClaytonSiby  :wave: 
## Good attempts on this one :muscle: :+1: 

## Your project looks great! but is a very important thing you have to consider before submitting another code review :point_down: 

### Page structure

#### Navigation bar
- [ ]  Titles should be centered in between of each paragraph
  >Basically you're missing some bottom padding In them 
##### Example
Screenshot from 2020-04-03 08-00-58
##### Yours:
Screenshot from 2020-04-03 08-00-25

#### Navigation bar
- [ ]  Your Login Buttons should have the text-align in the center 
##### Required:
Screenshot from 2020-04-03 07-56-49
##### Yours:
Screenshot from 2020-04-03 07-57-00

#### Editor's Picks Section
- [ ]  Element aren't aligned well, the first element have more space than the other elements
##### Required:
Screenshot from 2020-04-03 07-57-16
##### Yours:
Screenshot from 2020-04-03 07-58-35

#### Iline Message
- [ ]  Inline message before the section of 'As Big as It Gets' is missing
##### example:
Screenshot from 2020-04-03 07-59-08

#### As Big as It Gets Section
- [ ]  Video isn't align with your text
##### Required:
Screenshot from 2020-04-03 08-00-07
##### Yours:
Screenshot from 2020-04-03 07-59-41
- [ ]  Image isn't align with your text
##### Required:
Screenshot from 2020-04-03 08-00-46
##### Yours:
Screenshot from 2020-04-03 08-00-34

#### Footer
- [ ] It should have a fixed position (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

## Kindly address all these changes and submit a new code review

### Happy coding:computer: 

#### Daniel Laloush

**Comment by thsvr** [comment]
### STATUS: CHANGES REQUIRED :muscle: :muscle: 

Hi @evansinho and @ClaytonSiby :smile_cat: :smile_cat: 

Great job done so far! There are some required changes asked before which have to be implemented before the project can be approved. 

### **Below, there is a list of them. Can you please read it carefully** :+1:  and do the changes before ask for another code review? The screenshots were taken by Daniel on the last review, so if you need them, please go back on his instructions :smile: 

:v: As mentioned by Daniel(TSE), '' Titles should be centered in between of each paragraph". You guys need to fix 2 titles: "Spirals in the Sky," and "A Special Time" and others if there is more. Can you please consider it?

:v: As mentioned by Daniel(TSE), "your Login Buttons should have the text-align in the center.". Can you please fix it?

:v: As mentioned by Daniel(TSE), "image isn't align with your text", below the Spirals in the Sky, title. can you please fix it?

:v: As mentioned by Daniel(TSE), the footer ''should have a fixed position (it sticks to the bottom part of the screen)''. Can you please fix it?


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next review** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by evansinho** [comment]
thanks, @thsvr  for the quick review. But the changes have been implemented, please do check and get back to me. Thanks

**Review by men32z — APPROVED** [review]
## Good job making the changes, you can merge.

BlgS1sdIUAEybkW

### Status Approved

--Luis Preza

**Pull request merged**
